services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_DB: heal-link
      POSTGRES_USER: heal-link-user
      POSTGRES_PASSWORD: heal-link-pass

